#!/bin/bash

#disable this after first run
#sudo apt install libusb-1.0-0-dev libudev-dev

TOOLS="
mfcserver
mfcxtract"

for TOOL in $TOOLS
do
  echo Making $TOOL:
  cd $TOOL
  #make clean > /dev/null
  make
  cd ..
done

TOOLS1="
usbxtract/sw
clients/pcars
clients/assetto-corsa
clients/cm-f1
clients/cm-dr"

for TOOL in $TOOLS1
do
  echo Making $TOOL:
  cd $TOOL
  #make clean > /dev/null
  make
  cd ..
  cd ..
done

mkdir -p .mfc
cp mfcserver/mfc-main-svr .mfc/
cp mfcxtract/mfc-xtract   .mfc/
cp usbxtract/sw/usbxtract .mfc/usbxtract
cp clients/pcars/mfc-cli-pcars2     .mfc/
cp clients/assetto-corsa/mfc-cli-ac .mfc/
cp clients/cm-f1/mfc-cli-cm-f1      .mfc/
cp clients/cm-dr/mfc-cli-cm-drally  .mfc/

#.tar.gz
echo "compressing package.."
#tar -zcvf tar-archive-name.tar.gz source-folder-name
tar -zcvf mfc-v0.8.1-linux.tar.gz .mfc/*
echo "package ready"
#untar gz
#tar -zxvf tar-archive-name.tar.gz

echo "done."
